In [2]:
import torch

In [3]:
import numpy as np
torch.version.__version__

'1.10.2'

In [4]:
x = np.array([0,1,1])
w = [-10, 10, 5]
t_x = torch.from_numpy(x)
t_x.to('cuda')

tensor([0, 1, 1], device='cuda:0')

In [5]:
x = torch.arange(12, dtype=torch.float32)
print(x)
print("shape:", x.shape)
print("num element:", x.numel())

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])
shape: torch.Size([12])
num element: 12


In [6]:
x = x.reshape(3,4)
print(x)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [7]:
x = torch.zeros((2,3,4))
x.shape

torch.Size([2, 3, 4])

In [8]:
torch.randn((5,5)).to('cuda')

tensor([[-1.0868, -1.5748,  0.9127, -0.2144,  1.7797],
        [-0.2414, -0.4314, -1.0104,  1.2294,  1.0419],
        [ 1.0662,  1.5352,  0.5265,  0.7570, -0.3768],
        [-0.0872,  0.7395,  0.2257, -0.1999, -0.9070],
        [-2.0572, -0.0484, -1.5641,  0.6009, -1.2331]], device='cuda:0')

In [9]:
x = torch.tensor([1,2,3])
y = torch.tensor([2,2,2])
print('x + y', x+y)
print('x - y', x-y)
print('x * y', x*y)
print('x / y', x/y)
print('x ** y', x**y)

x + y tensor([3, 4, 5])
x - y tensor([-1,  0,  1])
x * y tensor([2, 4, 6])
x / y tensor([0.5000, 1.0000, 1.5000])
x ** y tensor([1, 4, 9])


In [10]:
x = torch.arange(12, dtype=torch.float32).reshape(3,4)
y = torch.tensor([[2.0, 1, 4, 3], [1,2,3,4], [4,3,2,1]])
z = torch.cat((x,y),dim=0)
z.shape


torch.Size([6, 4])

In [11]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [12]:
x.sum(dim=1)

tensor([ 6., 22., 38.])

### 2.1.3 Broadcasting Mechanism

In [13]:
a = torch.arange(3).reshape(3,1)
print('a', a)
b = torch.arange(2).reshape(1,2)
print('b', b)


a tensor([[0],
        [1],
        [2]])
b tensor([[0, 1]])


In [14]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 2.1.4 Indexing and Slicing

In [15]:
print('x:', x)
print('x[-1]:', x[-1])
print('x[1:3]:', x[1:3])

x: tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
x[-1]: tensor([ 8.,  9., 10., 11.])
x[1:3]: tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


### 2.1.5 Saving Memory

In [16]:
print(id(y))
y = y + x
print(id(y))
y += x
print(id(y))
y[:] = y + x
print(id(y))

139781321716896
139781321756560
139781321756560
139781321756560


In [17]:
z = torch.zeros(3,4)
print(id(z))
z[:] = y+x
print(id(z))

139787367911152
139787367911152


### 2.1.6 Conversion to Other Python Objects

In [21]:
a = x.numpy()
print('a:', type(a))
b = torch.from_numpy(a)
print('b:', type(b))


a: <class 'numpy.ndarray'>
b: <class 'torch.Tensor'>


In [30]:
a = torch.tensor(3.6)
a, a.item(), float(a), int(a)

(tensor(3.6000), 3.5999999046325684, 3.5999999046325684, 3)

In [32]:
x > y, x < y

(tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [35]:
a = torch.arange(3).reshape(3,1,1)
b = torch.arange(2).reshape(1,1,2)
a, b, a+b, (a + b).shape

(tensor([[[0]],
 
         [[1]],
 
         [[2]]]),
 tensor([[[0, 1]]]),
 tensor([[[0, 1]],
 
         [[1, 2]],
 
         [[2, 3]]]),
 torch.Size([3, 1, 2]))

## 2.2 Data Preprocessing

In [57]:
import os
import sys

this_dir = os.path.abspath('')
os.makedirs(os.path.join(this_dir, 'data'), exist_ok=True)
data_file = os.path.join(os.path.join('data', 'house_tiny.csv'))
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [58]:
import pandas as pd
data = pd.read_csv(data_file)
data,

(   NumRooms Alley   Price
 0       NaN  Pave  127500
 1       2.0   NaN  106000
 2       4.0   NaN  178100
 3       NaN   NaN  140000,)

### 2.2.2 Handling Missing Data

In [59]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


/tmp/ipykernel_2478417/38268100.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  inputs = inputs.fillna(inputs.mean())
